### ISSUE TITLE
Cannot run binaries downloaded from Releases

### ISSUE THREAD

**Issue by VeyronSakai** [termkit/gama#56]
## Overview

This is to report that I could not execute the v1.1.4 Binary downloaded from [Releases](https://github.com/termkit/gama/releases/tag/v1.1.4).

## Verification environment

OS: macOS Sonoma 14.4.1
Chip: Apple M2 Max

## Procedure

1. I downloaded gama-macos-arm64 v1.1.4 from [Releases](https://github.com/termkit/gama/releases/tag/v1.1.4).
2. I double-clicked the downloaded gama-macos-arm64 file.
3. A popup appeared that said "gama-macos-arm64 cannot be opened because it is from unidentified developer."
4. I selected "Open Anyway" under Privacy & Security in macOS System Settings.
5. I selected "Open" when the popup "macOS cannot verify the developer of gama-macos-arm64. Are you sure you want to open it?"
6. The contents of the binary file have been opened. (Is it not recognized as an executable file?)

## Other things I tried

```sh
chmod +x gama-macos-arm64
```

After executing the above commands, I tried the same procedure and were able to successfully launch the application.

**Comment by canack** [comment]
The issue stems from macOS's security policy, which blocks unrecognized apps to protect your Mac. It's Apple's way of keeping you safe from harmful software.

However, you found a workaround by using `chmod +x` and opting for "Open Anyway". This is a great solution that allows macOS to accept the application.

Alternatively, downloading the binary with `wget` or `curl` might sidestep some of these security prompts:

```sh
wget https://github.com/termkit/gama/releases/download/v1.1.4/gama-macos-arm64
```

And don't forget to make it executable:

```sh
chmod +x gama-macos-arm64
```

This method offers a smooth path past macOS's security checks, ensuring you can use your apps without hassle.

Note: I think to add `go install` method to install GAMA. But go install, installs the application directly the source. This is a little problem for us because the version of gama, setting at build stage as build argument.

**Comment by VeyronSakai** [comment]
Thank you very much for your kind attention!
